# Generated by Django 5.2 on 2025-05-07 22:48

import django.db.models.deletion
import securite.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlerteAcces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Inconnu', max_length=100, verbose_name="Nom de l'alerte")),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('statut', models.CharField(choices=[('intrus', 'Intrus détecté'), ('acces_non_autorise', 'Accès non autorisé'), ('acces_autorise', 'Accès autorisé'), ('pending', 'En attente de traitement')], default='pending', max_length=20, verbose_name="Statut de l'alerte")),
                ('confiance', models.FloatField(default=0.0, verbose_name='Niveau de confiance')),
                ('details', models.TextField(blank=True, null=True, verbose_name='Détails supplémentaires')),
                ('vecteur_visage', models.BinaryField(blank=True, null=True, verbose_name='Vecteur facial anonymisé')),
                ('date_expiration', models.DateTimeField(default=securite.models.default_expiration_date, verbose_name="Date d'expiration RGPD")),
                ('est_anonyme', models.BooleanField(default=True, verbose_name='Données anonymisées')),
            ],
            options={
                'verbose_name': "Alerte d'accès",
                'verbose_name_plural': "Alertes d'accès",
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='IntrusImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='intrus/', verbose_name="Image de l'intrus")),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
            ],
            options={
                'verbose_name': "Image d'intrus",
                'verbose_name_plural': "Images d'intrus",
            },
        ),
        migrations.CreateModel(
            name='PersonneAutorisee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom complet')),
                ('image', models.ImageField(upload_to='personnes_autorisees/', verbose_name='Photo de référence')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('date_expiration', models.DateTimeField(blank=True, null=True, verbose_name="Date d'expiration")),
            ],
            options={
                'verbose_name': 'Personne autorisée',
                'verbose_name_plural': 'Personnes autorisées',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='TentativeIntrusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Inconnu', max_length=100, verbose_name="Nom de l'intrus")),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Date et heure')),
                ('confiance', models.FloatField(default=0.0, verbose_name='Niveau de confiance')),
                ('statut', models.CharField(default='en_attente', max_length=100, verbose_name='Statut')),
                ('capture', models.ImageField(blank=True, null=True, upload_to='intrus/', verbose_name="Capture d'écran")),
            ],
            options={
                'verbose_name': "Tentative d'intrusion",
                'verbose_name_plural': "Tentatives d'intrusion",
                'ordering': ['-datetime'],
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse email')),
                ('telephone', models.CharField(max_length=20, verbose_name='Numéro de téléphone')),
                ('recoit_sms', models.BooleanField(default=False, verbose_name="Reçoit les SMS d'alerte")),
                ('recoit_email', models.BooleanField(default=True, verbose_name="Reçoit les emails d'alerte")),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur associé')),
            ],
            options={
                'verbose_name': 'Agent de sécurité',
                'verbose_name_plural': 'Agents de sécurité',
                'ordering': ['nom'],
            },
        ),
    ]
