# Generated by Django 5.2 on 2025-05-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alerteacces',
            options={'ordering': ['-date'], 'verbose_name': 'Alerte sécurisée', 'verbose_name_plural': 'Alertes sécurisées'},
        ),
        migrations.RemoveField(
            model_name='alerteacces',
            name='details',
        ),
        migrations.AddField(
            model_name='alerteacces',
            name='action_prise',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Action de sécurité'),
        ),
        migrations.AddField(
            model_name='alerteacces',
            name='date_action',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dernière action'),
        ),
        migrations.AddField(
            model_name='alerteacces',
            name='hash_securise',
            field=models.CharField(blank=True, help_text='SHA256 des données vectorielles', max_length=64, null=True, verbose_name='Hash anonyme'),
        ),
        migrations.AddField(
            model_name='alerteacces',
            name='metadata',
            field=models.JSONField(default=dict, help_text='Données contextuelles non-identifiantes', verbose_name='Métadonnées techniques'),
        ),
        migrations.AlterField(
            model_name='alerteacces',
            name='confiance',
            field=models.FloatField(default=0.0, help_text='Probabilité estimée de la menace (0-100%)', verbose_name='Niveau de confiance (%)'),
        ),
        migrations.AlterField(
            model_name='alerteacces',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Horodatage création'),
        ),
        migrations.AlterField(
            model_name='alerteacces',
            name='est_anonyme',
            field=models.BooleanField(default=True, verbose_name='Anonymisation validée'),
        ),
        migrations.AlterField(
            model_name='alerteacces',
            name='nom',
            field=models.CharField(default='Inconnu', max_length=100, verbose_name='Identifiant alerte'),
        ),
        migrations.AlterField(
            model_name='alerteacces',
            name='statut',
            field=models.CharField(choices=[('intrus', 'Intrus détecté'), ('acces_non_autorise', 'Accès non autorisé'), ('acces_autorise', 'Accès autorisé'), ('pending', 'En attente de traitement'), ('expire', 'Données expirées')], default='pending', max_length=20, verbose_name='Niveau de menace'),
        ),
        migrations.AlterField(
            model_name='alerteacces',
            name='vecteur_visage',
            field=models.BinaryField(blank=True, help_text='Vecteur flouté et réduit (32x32px)', null=True, verbose_name='Empreinte biométrique sécurisée'),
        ),
        migrations.AddIndex(
            model_name='alerteacces',
            index=models.Index(fields=['date'], name='securite_al_date_8abf33_idx'),
        ),
        migrations.AddIndex(
            model_name='alerteacces',
            index=models.Index(fields=['statut'], name='securite_al_statut_75b239_idx'),
        ),
    ]
