# Generated by Django 5.2 on 2025-05-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securite', '0002_alter_alerteacces_options_remove_alerteacces_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tentativeintrusion',
            name='capture',
            field=models.ImageField(blank=True, null=True, upload_to='alertes/', verbose_name="Capture de l'intrus"),
        ),
    ]
