# Generated by Django 5.2 on 2025-05-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securite', '0003_alter_tentativeintrusion_capture'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerteacces',
            name='details',
            field=models.TextField(blank=True),
        ),
    ]
