# Generated by Django 5.2 on 2025-05-12 20:05

# securite/migrations/0005_alerteacces_date_creation.py
from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):
    # Vérifiez que cette dépendance pointe vers votre dernière migration valide
    dependencies = [
        ('securite', '0004_alerteacces_details'),  # Remplacez par le vrai nom
    ]

    operations = [
        migrations.AddField(
            model_name='alerteacces',
            name='date_creation',
            field=models.DateTimeField(
                auto_now_add=True,
                default=timezone.now
            ),
            preserve_default=True,
        ),
    ]