# Generated by Django 5.2 on 2025-05-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securite', '0005_alerteacces_date_creation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alerteacces',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Alerte sécurisée', 'verbose_name_plural': 'Alertes sécurisées'},
        ),
        migrations.AlterField(
            model_name='alerteacces',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
