# Generated by Django 5.2 on 2025-05-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('securite', '0006_alter_alerteacces_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerteacces',
            name='vecteur_visage',
            field=models.BinaryField(blank=True, null=True, verbose_name='Empreinte biométrique sécurisée'),
        ),
    ]
